# ===============================
# CONFIGURAZIONE DATABASE (AWS RDS)
# ===============================

spring.datasource.url=jdbc:postgresql://wms-database.cfo8my6uslea.eu-north-1.rds.amazonaws.com:5432/wms_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# ===============================
# CONFIGURAZIONE SERVER WEB
# ===============================
server.port=8080

# Evita che il DB o AWS chiudano la connessione prima di Hikari.
spring.datasource.hikari.max-lifetime=540000

# 2. Ogni 4 minuti (240000 ms) fai un "ping" al database
spring.datasource.hikari.keepalive-time=240000

# 3. Tempo massimo di attesa per una connessione
spring.datasource.hikari.connection-timeout=30000

# 4. Aumenta il pool di connessioni
spring.datasource.hikari.maximum-pool-size=20

# 5. Tempo massimo di inattività prima che Hikari chiuda la connessione per risparmiare risorse (deve essere < max-lifetime)
spring.datasource.hikari.idle-timeout=300000

# ===============================
# LOGGING (Per vedere le query in console)
# ===============================
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG

spring.jpa.hibernate.ddl-auto=update

# FORZA L'ATTIVAZIONE DELLA CONSOLE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console