# ===============================
# CONFIGURAZIONE DATABASE (AWS RDS)
# ===============================
spring.datasource.url=jdbc:postgresql://wms-database.cfo8my6uslea.eu-north-1.rds.amazonaws.com:5432/wms_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAZIONE SERVER WEB
# ===============================
server.port=8080

# ===============================
# LOGGING (Per vedere le query in console)
# ===============================
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG