name: Spring Boot CD/CI Pipeline

on:
  push:
    branches: [ "**" ] #[ "main", "master" ] se voglio specificare i branch, altrimenti "**" per tutti i branch
  pull_request:
    branches: [ "main", "master" ] # Conviene mettere solo main e master per evitare doppie esecuzionii

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven 

    - name: Compila e Testa con Maven
      run: mvn clean verify